name: Releases

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: build pyz file
      run: |
        make build
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "_build/*.pyz"
